# Generated by Django 4.1.7 on 2023-03-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_start_periodically_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, null=True, verbose_name="user name"),
        ),
    ]
