# Generated by Django 4.1.7 on 2023-03-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="user name"
            ),
        ),
    ]
