version: "3.9"

services:
  db:
    image: postgres:15.1
    env_file:
      .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/src
      - static:/static
    env_file:
      - .env

    command: /bin/bash -c "pip install -r requirements.txt && invoke runit"

  nginx:
    image: nginx:1.23.3
    networks:
      - default
      - nginx-proxy
    volumes:
      - static:/static:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    environment:
      - VIRTUAL_HOST=hillel.ryzhenko.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=hillel.ryzhenko.com
      - LETSENCRYPT_EMAIL=admin@hillel.ryzhenko.com


networks:
  defaul:
  nginx-proxy:
    name: nginx-proxy

volumes:
  pgdata:
  static: