version: "3.9"

services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "lesson-9"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/src
    environment:
      DJANGO_SETTINGS_MODULE: "settings.docker"
      POSTGRES_PASSWOED: "123"

volumes:
  pgdata:
