version: "3.9"

services:
  db:
    image: postgres:15.1
    env_file:
      .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/src
      - static:/static
    env_file:
      - .env

    command: /bin/bash -c "pip install -r requirements.txt && invoke runit"

  nginx:
    image: nginx:1.23.3
    volumes:
      - static:/static:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_PORT}:80"

volumes:
  pgdata:
  static: